# coding: utf-8

"""
    API управления приборами

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from service.models.feature import Feature
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DeviceState(BaseModel):
    """
    DeviceState
    """ # noqa: E501
    status: Optional[StrictStr] = None
    timestamp: Optional[StrictInt] = None
    features: Dict[str, Feature]
    __properties: ClassVar[List[str]] = ["status", "timestamp", "features"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('online', 'offline', 'active', 'busy',):
            raise ValueError("must be one of enum values ('online', 'offline', 'active', 'busy')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DeviceState from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in features (dict)
        _field_dict = {}
        if self.features:
            for _key in self.features:
                if self.features[_key]:
                    _field_dict[_key] = self.features[_key].to_dict()
            _dict['features'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DeviceState from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "timestamp": obj.get("timestamp"),
            "features": dict(
                (_k, Feature.from_dict(_v))
                for _k, _v in obj.get("features").items()
            )
            if obj.get("features") is not None
            else None
        })
        return _obj


