# coding: utf-8

"""
    API управления приборами

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class Feature(BaseModel):
    """
    Feature
    """ # noqa: E501
    type: StrictStr
    unit: StrictStr
    timestamp: Optional[StrictInt] = None
    childs: Optional[Dict[str, Feature]] = None
    value: Optional[Any]
    __properties: ClassVar[List[str]] = ["type", "unit", "timestamp", "childs", "value"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Feature from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in childs (dict)
        _field_dict = {}
        if self.childs:
            for _key in self.childs:
                if self.childs[_key]:
                    _field_dict[_key] = self.childs[_key].to_dict()
            _dict['childs'] = _field_dict
        # set to None if value (nullable) is None
        # and model_fields_set contains the field
        if self.value is None and "value" in self.model_fields_set:
            _dict['value'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of Feature from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "unit": obj.get("unit"),
            "timestamp": obj.get("timestamp"),
            "childs": dict(
                (_k, Feature.from_dict(_v))
                for _k, _v in obj.get("childs").items()
            )
            if obj.get("childs") is not None
            else None,
            "value": obj.get("value")
        })
        return _obj

# TODO: Rewrite to not use raise_errors
Feature.model_rebuild(raise_errors=False)

