openapi: 3.1.0
info:
  title: API управления приборами
  version: 0.0.1

components:
  schemas:
    SuccessMessage:
      type: object
      properties:
        message:
          type: string

    ErrorMessage:
      type: object
      properties:
        message:
          type: string
        code:
          type: integer

    Feature:
      type: object
      required:
      - value
      - type
      - unit
      properties:
        type:
          type: string
        unit:
          type: string
        timestamp:
          type: integer
        childs:
          type: 'object'
          additionalProperties:
            $ref: '#/components/schemas/Feature'
        value: {}

    DeviceState:
      type: object
      required:
      - features
      properties:
        status:
          enum:
          - online
          - offline
          - active
          - busy
        timestamp:
          type: integer
        features:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/Feature'

    DeviceMeta:
      type: object
      required:
      - kind
      - model
      - serialnum
      properties:
        kind:
          type: string
        model:
          type: string
        serialnum:
          type: string

  requestBodies:
    DeviceTargetState:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DeviceState'

    DeviceMeta:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DeviceMeta'

  responses:
    SuccessResponse:
      description: |
        Ответ на любую успешную операцию.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SuccessMessage'

    ErrorResponse:
      description: |
        Ответ на некорректную операцию.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'

    DeviceStateResponse:
      description: Состояние прибора.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DeviceState'

    AuthenticationErrorResponse:
      description: |
        Не был предоставлен токен авторизации, сервер не может обработать
        запрос.
      $ref: '#/components/responses/ErrorResponse'

paths:
  /v1/control/{provider}/{protocol}/{address}:
    get:
      operationId: 'v1InspectDevice'
      summary: Получение состояния прибора.
      description: Получение полного состояния прибора.
      parameters:
        - $ref: 'common.yaml#/components/parameters/ProviderParam'
        - $ref: 'common.yaml#/components/parameters/ProtocolParam'
        - $ref: 'common.yaml#/components/parameters/AddressParam'
      responses:
        "200":
          $ref: '#/components/responses/DeviceStateResponse'
        "401":
          $ref: '#/components/responses/AuthenticationErrorResponse'
        "404":
          description: |
            Прибор не найден по переданным параметрам - не поддерживаются
            указанные провайдер или протокол, не находится по адресу, либо
            управление этим прибором не запущено.
          $ref: '#/components/responses/ErrorResponse'
    post:
      operationId: 'v1ConnectDevice'
      summary: Запуск управления прибором
      description: |
        Создаёт сеанс управления прибором и запрашивает его начальное
        состояние. Требует данных по модели прибора и его типу (а также
        возможно и по серийному номеру) определить необходимый протокол
        взаимодействия. Это сделано для того, чтобы поддерживать приборы,
        которые не поддерживают рефлексию, с помощью которой можно выявить, по
        каким протоколам можно взаимодействовать и какие функциональные
        возможности есть. Для приборов, которые поддерживают рефлекцию, данная
        информация может быть проигнорирована.
      parameters:
        - $ref: 'common.yaml#/components/parameters/ProviderParam'
        - $ref: 'common.yaml#/components/parameters/ProtocolParam'
        - $ref: 'common.yaml#/components/parameters/AddressParam'
      requestBody:
        $ref: '#/components/requestBodies/DeviceMeta'
      responses:
        "201":
          $ref: '#/components/responses/DeviceStateResponse'
        "401":
          $ref: '#/components/responses/AuthenticationErrorResponse'
        "404":
          description: |
            Прибор не найден по переданным параметрам - не поддерживаются
            указанные провайдер или протокол, не находится по адресу.
          $ref: '#/components/responses/ErrorResponse'
    patch:
      operationId: 'v1RunDevice'
      summary: Установка целевого состояния прибора.
      description: Установка целевого состояния прибора.
      parameters:
        - $ref: 'common.yaml#/components/parameters/ProviderParam'
        - $ref: 'common.yaml#/components/parameters/ProtocolParam'
        - $ref: 'common.yaml#/components/parameters/AddressParam'
      requestBody:
        $ref: '#/components/requestBodies/DeviceTargetState'
      responses:
        "202":
          description: Команда принята на обработку.
          $ref: '#/components/responses/SuccessResponse'
        "401":
          $ref: '#/components/responses/AuthenticationErrorResponse'
        "400":
          description: |
            Передано неправильное состояние или прибор не поддерживает атрибуты
            переданного состояния.
          $ref: '#/components/responses/ErrorResponse'
        "403":
          description: Состояние прибора невозможно изменить.
          $ref: '#/components/responses/ErrorResponse'
        "404":
          description: |
            Прибор не найден по переданным параметрам - не поддерживаются
            указанные провайдер или протокол, не находится по адресу.
          $ref: '#/components/responses/ErrorResponse'
        "422":
          description: Прибор недоступен или не способен ответить на команду.
          $ref: '#/components/responses/ErrorResponse'
    delete:
      operationId: 'v1DisconnectDevice'
      summary: Останов управления прибором
      description: |
        Останавливает сеанс управления прибором и удаляет его состояние из
        системы.
      parameters:
        - $ref: 'common.yaml#/components/parameters/ProviderParam'
        - $ref: 'common.yaml#/components/parameters/ProtocolParam'
        - $ref: 'common.yaml#/components/parameters/AddressParam'
      responses:
        "200":
          $ref: '#/components/responses/SuccessResponse'
        "401":
          $ref: '#/components/responses/AuthenticationErrorResponse'
        "404":
          description: |
            Прибор не найден по переданным параметрам - не поддерживаются
            указанные провайдер или протокол, не находится по адресу.
          $ref: '#/components/responses/ErrorResponse'
