# config/debezium/application.properties
## sink config
debezium.sink.type=redis
debezium.sink.redis.address=cdc_bus:6379
debezium.sink.redis.null.value='NULL'
debezium.sink.redis.null.key='NULL'

debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector
debezium.source.offset.storage.file.filename=data/offsets.dat
debezium.source.offset.flush.interval.ms=5000
debezium.source.database.hostname=postgres
debezium.source.database.port=5432
debezium.source.database.user=iot
debezium.source.database.password=iot
debezium.source.database.dbname=smarthome
debezium.source.topic.prefix=warmhouse_devices
debezium.source.table.include.list=public.sensors
debezium.source.plugin.name=pgoutput
debezium.source.publication.name=warmhouse_cdc
debezium.source.tombstones.on.delete=false

debezium.format.value=json
debezium.format.key=json

debezium.transforms=unwrap
debezium.transforms.unwrap.type=io.debezium.transforms.ExtractNewRecordState
debezium.transforms.unwrap.drop.tombstones=false
debezium.transforms.unwrap.delete.handling.mode=rewrite
debezium.transforms.unwrap.add.fields=op,db,table,schema,lsn,source.ts_ms

quarkus.log.console.json=false
quarkus.log.file.enable=false
quarkus.log.level=INFO
