"""extend devices table

Revision ID: 4a6d5632c8c0
Revises: f2aad89c2cb1
Create Date: 2025-11-08 13:10:48.125101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a6d5632c8c0'
down_revision: Union[str, None] = 'f2aad89c2cb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('kind', sa.String(), nullable=False))
    op.add_column('devices', sa.Column('serialnum', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'serialnum')
    op.drop_column('devices', 'kind')
    # ### end Alembic commands ###
