@startuml

package warmhouse.device.client {
    class DeviceCommunicator <<module>> {
        - deviceClients: DeviceClient[]
        + state(deviceId: DeviceID): DeviceState
        + run(deviceId: DeviceID, newState: DeviceState): CommandResult
        + onEvent(deviceEventHandler: Function<DeviceState>)
    }

    class DeviceState {
        + deviceId: DeviceID
        + status: DeviceStatus
        + timestamp: Timestamp
        + features(): Feature[]
    }

    class DeviceID {
        + protocol: Protocol
        + id: String
    }

    class Feature {
        + attributes(): Attribute[]
        + childs(): Feature[]
    }

    struct Attribute {
        + name: String
        + type: Type
        + value: Any
        + unit: MeasurableUnit
        + timestamp: Timestamp
    }

    enum Protocol {
        + MQTT
        + CoAP
        + HTTP
    }

    enum DeviceStatus {
        + online
        + offline
        + active
        + busy
    }

    class CommandResult {
        statusCode: integer
        state: DeviceState
    }

    interface DeviceClient {
        + state(deviceId: DeviceID): DeviceState
        + run(deviceId: DeviceID, command: DeviceCommand): CommandResult
        + onEvent(deviceEventHandler: Function<DeviceState>)
    }

    class DeviceMQTTClient
    class DeviceHTTPClient
    class DeviceCoAPClient
}


DeviceMQTTClient ..|> DeviceClient
DeviceHTTPClient ..|> DeviceClient
DeviceCoAPClient ..|> DeviceClient
DeviceClient "*" --* "1" DeviceCommunicator

DeviceID --> Protocol
Feature "1" --* "*" Feature
Attribute "*" --* "1" Feature

Feature "1" --* "*" DeviceState
DeviceState "1" --* "1" CommandResult
DeviceID "1" --* "1" DeviceState

DeviceCommunicator --> DeviceID : использует
DeviceCommunicator --> CommandResult : порождает
DeviceCommunicator --> DeviceState: порождает
DeviceState "1" --> "1" DeviceStatus

@enduml
