@startuml

package warmhouse.device.manager {
    class DeviceManager {
        + start(deviceId: DeviceID, userId: String)
        + stop(deviceId: DeviceID, userId: String)
        + run(deviceId: DeviceState, userId: String)
        + state(deviceId: DeviceID)
    }

    class DeviceRegistryClient {
        + getDeviceInfo(userId: String, deviceId: DeviceID)
    }

    note right of DeviceManager::start
    POST /v1/devices
    end note

    note right of DeviceManager::stop
    DELETE /v1/devices/{deviceId}
    end note

    note right of DeviceManager::run
    PUT /v1/devices/{deviceId}
    PATCH /v1/devices/{deviceId}
    end note

    note right of DeviceManager::state
    GET /v1/devices/{deviceId}
    end note
}

package warmhouse.device.client {
    class DeviceDigTwin
    class DeviceClient
}

DeviceManager --> DeviceDigTwin
DeviceManager --> DeviceClient
DeviceManager --> DeviceRegistryClient

@enduml
