@startuml

package warmhouse.device.digtwin {
    class DeviceDigTwin {
        - cache: DeviceStateCache
        - queue: TelemetryQueue
        + update(state: DeviceState)
        + state(deviceId: DeviceID): DeviceState
        + bind(deviceId: DeviceID, user: String)
        + devices(since: Timestamp): DeviceState[]
    }

    class StateMerger {
        old: DeviceState
        new: DeviceState
        + mergeable(): boolean
        + merge(): DeviceState
    }

    class TelemetryQueue {
        publish(message: Any)
    }

    class DeviceStateCache {
        store(state: DeviceState)
        get(deviceId: DeviceID)
    }
}

package warmhouse.device.client {
    class DeviceState
    class DeviceID
}

DeviceStateCache --o DeviceDigTwin
DeviceStateCache ..> DeviceID : основной способ идентификации приборов
TelemetryQueue --o DeviceDigTwin

DeviceDigTwin --> StateMerger : cравнение и обновление состояний
DeviceState "2" --o "1" StateMerger
DeviceDigTwin ..> DeviceState : использует в качестве основной структуры
DeviceDigTwin ..> DeviceID : основной способ идентификации приборов

@enduml
