# coding: utf-8

"""
    API реестра приборов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from service.apis.default_api import router as DefaultApiRouter
import service.repository as repository

app = FastAPI(
    title="API реестра приборов",
    description="No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)",
    version="0.0.1",
)

app.include_router(DefaultApiRouter)

@app.on_event("startup")
async def init():
    await repository.init()
