@startuml
!include <C4/C4_Container>
!include <C4/C4_Context>

'LAYOUT_LANDSCAPE()


System_Boundary(warmhouseIoTEcosystem, "Экосистема Тёплый дом") {
    System_Boundary(warmhouseIoT, "Тёплый дом") {
        '---------------------------------------------------------------------
        '- Контекст управления приборами
        '---------------------------------------------------------------------
        Container(DevicesController, "Управление приборами", \
                  $descr="Передача команд, получение ответов, цифровые двойники приборов")
        ContainerDb(DevicesControllerCache, "Горячий кеш состояния приборов", \
                    $descr="Хранение состояния цифровых двойников")
        Rel(DevicesController, DevicesControllerCache, "Хранит состояние")

        '---------------------------------------------------------------------
        '- Контекст хранения сведений о приборах
        '---------------------------------------------------------------------
        Container(Devices, "Реестр приборов", \
                  $descr="Регистрация приборов, удаление приборов из системы, привязка к пользователям")
        ContainerDb(DevicesDB, "База данных приборов")
        Rel(Devices, DevicesDB, "Хранит данные")

        '---------------------------------------------------------------------
        '- Контекст обработки телеметрии
        '---------------------------------------------------------------------
        Container(Telemetry, "Телеметрия", \
                  $descr="Сбор, хранение, выдача телеметрических данных")
        ContainerDb(TelemetryDB, "База данных телеметрии")
        Rel_R(Telemetry, TelemetryDB, "Хранит данные")
        ContainerQueue(TelemetryBus, "Шина телеметрических данных", \
                       $descr="Очередь с событиями телеметрии")

        '---------------------------------------------------------------------
        '- Контекст управления пользователями
        '---------------------------------------------------------------------
        Container(Users, "Реестр пользователей", \
                  $descr="Регистрация пользователей, их удаление, хранение пользовательских данных")
        ContainerDb(UsersDB, "База данных пользователей")
        Rel(Users, UsersDB, "Хранит данные")

        '---------------------------------------------------------------------
        '- Контекст управления размещением приборов
        '---------------------------------------------------------------------
        Container(Placements, "Размещение приборов", \
                  $descr="Управление размещениями, привязка приборов к месту")
        ContainerDb(PlacementsDB, "База данных размещений")
        Rel(Placements, PlacementsDB, "Хранит данные")
    }

    Rel_R(DevicesController, Devices, "Получает сведения о приборе и его привязках к пользователю", "HTTPS")
    Rel_L(Devices, DevicesController, "Поиск приборов, подключенных к системе", "HTTPS")
    Rel(DevicesController, TelemetryBus, "Публикует события телеметрии")
    Rel_U(TelemetryBus, Telemetry, "Обрабатывает события телеметрии")

    System(Device, "Прибор экосистемы Тёплый Дом", $sprite="robot")
    BiRel(DevicesController, Device, "Управление приборами", "MQTT, HTTP, ...")

    System(Client, "Клиентское приложение", $sprite="robot", $type="Web, Android, iOS, Aurora")
}

Person(User, "Пользователь")
Rel(User, Client, "")

Rel(Client, Users, "Регистрируется, авторизуется, аутентифицируется", "HTTPS")
Rel(Client, Devices, "Привязывает приборы к своей учётной записи, отвязывает их от неё, \
                      задаёт дополнительные сведения", "HTTPS")
Rel(Client, Telemetry, "Получает текущее состояние приборов, историю состояния", "HTTPS, WSS")
Rel(Client, Placements, "Задаёт места для размещения приборов, привязывает приборы к местам", "HTTPS")
Rel(Client, DevicesController, "Управляет приборами", "HTTPS")

Lay_U(DevicesController, Device)
Lay_L(DevicesController, TelemetryBus)

@enduml
